name: CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  validate:
    name: Validate Project
    runs-on: ubuntu-latest

    steps:

      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4


      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      # Install ShellCheck
      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck


      # Lint shell scripts
      - name: Run ShellCheck
        run: |
          find . -type f -name "*.sh" -print0 |
            xargs -0 -r shellcheck


      # Validate Bash syntax
      - name: Run Bash syntax check
        run: |
          find . -type f -name "*.sh" -print0 |
            xargs -0 -r bash -n